### ISSUE TITLE
'Module' object has no attribute 'file_stream'

### ISSUE THREAD

**Issue by shahi645** [ONSdigital/eq-schema-validator#22] opened 2018-02-01 10:52 UTC
Just a warning from flake8 as pictured below, will need a little investigating. 

<img width="692" alt="screen shot 2018-02-01 at 10 52 21" src="https://user-images.githubusercontent.com/22025926/35674893-07f3e4aa-073e-11e8-8458-de8965212e53.png">

**Comment by jonnyshaw89** [comment] 2018-02-01 10:57
We had this error on runner @ajmaddaford fixed it with help from @dwyeradam.
One thing to note is that with this error linting is not happening.

**Comment by jonnyshaw89** [comment] 2018-02-02 09:28
If this is caused by https://github.com/ONSdigital/eq-schema-validator/pull/20 and that PR isn't merged. Is this an issue yet?

**Comment by shahi645** [comment] 2018-02-02 09:33
@jonnyshaw89 me and @nealedj looked into this yesterday, it is not a result of #20

**Comment by jonnyshaw89** [comment] 2018-02-02 09:44
@shahi645 i disagree. I have just run lint on master and it works.
I switch to the branch in #20 and it fails

**Comment by jonnyshaw89** [comment] 2018-02-02 09:45
When testing this you need to delete your virtual env between each branch

**Comment by shahi645** [comment] 2018-02-02 10:38
Will try this also

**Comment by jonnyshaw89** [comment] 2018-02-02 10:40
This is my output before and after changing from master to #20 
![screen shot 2018-02-02 at 10 39 35](https://user-images.githubusercontent.com/7594012/35729044-678779d2-0805-11e8-9851-c7337b0096f9.png)

**Comment by shahi645** [comment] 2018-02-02 10:44
@jonnyshaw89 little update, so its not the version that causes this but the `required ` attribute, so gonna wait for the mad dawg to advise

**Comment by shahi645** [comment] 2018-02-02 10:44
#20 on hold until then

**Comment by ajmaddaford** [comment] 2018-02-05 11:22
When we had this issue on survey runner it was due to an incompatibility between the pylint-mcabe and astroid modules - https://github.com/ONSdigital/eq-survey-runner/pull/1418. It was fixed by pinning astroid to version 1.5.3.

**Comment by ajmaddaford** [comment] 2018-02-09 15:16
Closing this as it's an issue in an un-merged pull request, the fix is being tracked there.

**Closed by ajmaddaford** 2018-02-09 15:16 UTC
Labels: help wanted
